version: '2'
services:
  rpi-node:
    image: python:2
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "python -u run.py"
    networks:
      - smart-remote_rpi-net

networks:
  smart-remote_rpi-net:
    external: true
